### ISSUE TITLE
Capacitorjs support

### ISSUE THREAD

**Issue by geoman2** [eduardoRoth/analog-ionic-capacitor-template#1]
Hi
Have you considered to add Capacitorjs support to this stack?

**Comment by eduardoRoth** [comment]
Hi @geoman2 , Capacitor is already installed in this template. You only need to add the platforms you want

```
npx cap add android
npx cap add ios
```

And then sync the project

```
npx cap sync
```

And you can run the app with

```
npx cap run android
npx cap run ios
```
